### ISSUE TITLE
visibility and initialization

### ISSUE THREAD

**Issue by lprone** [M-Sin/CircuitBuilder#8]
https://github.com/M-Sin/CircuitBuilder/blob/127d1020c250644fede8f327916cf704f041081c/CircuitBuilder/src/circuit/Voltage.java#L17

You can define this field as a private and initialize it in Voltage constructor

**Comment by M-Sin** [comment]
Hi thanks for all your help. Regarding this point, it needs to be a static variable so that every voltage object has access to the same 'voltage number'. And if I attempt to initialize it in the constructor, I will simply be overwriting the static variable. Currently, when the first voltage object is made, the static variable is initialized by having that line you referenced, and constructor will increase the voltage id number after assigning the current number to the object being created. So I do not think I am able to make this change, unless I am understanding something wrong.

**Comment by lprone** [comment]
Checking again I think you could create a new class like a helper to update and return the vNum value  like this: 

`
class ComponentNumerator {
    private static int vNum;

    public static int getVnum(){
        vNum++;
        return vNum;
    }
}
`

and replace this block:

`
        this.setId(Voltage.vnum);
        Voltage.vnum++;
`

by this: 

`
this.setId(ComponentNumerator.getVnum());
`

Doing that you'll get classes with single responsabilities.

**Comment by M-Sin** [comment]
Given that I wouldn't need to create an object of this class, would it not still use a lot more resources to have an entire class to hold the static variable compared to just looking at a static variable within the current class as it is? I think if my classification system needed to get more complicated then a helper function would definitely be justified. I think in the case I would leave the static variable to be handled by the class for each component.
